# Generated by Django 3.0 on 2022-01-30 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forumpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forumpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
